# Generated by Django 4.2.2 on 2023-06-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_bb_additionalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30, verbose_name='Автор')),
                ('content', models.TextField(max_length=5000, verbose_name='Содержание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отобразить комментарий')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bb', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_time'],
            },
        ),
    ]
